-- Sprint 4a: Pipeline automation
ALTER TABLE leads ADD COLUMN IF NOT EXISTS unsubscribed BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS is_stale BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS stale_snoozed_until TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS re_engage_after TIMESTAMPTZ;
