export const mockLeads = [
  {
    id: "1",
    name: "Sarah Chen",
    title: "VP of Engineering",
    company: "TechFlow Inc",
    email: "sarah.chen@techflow.io",
    phone: "+1 (415) 555-0142",
    website: "techflow.io",
    location: "San Francisco, CA",
    industry: "Software",
    employees: 120,
    revenue: "$15M",
    status: "new",
    hotScore: 92,
    source: "google-maps",
    addedAt: "2025-01-15",
    notes: "Looking for lead gen automation tools",
    social: { linkedin: "linkedin.com/in/sarahchen" },
  },
  {
    id: "2",
    name: "Marcus Rivera",
    title: "Marketing Director",
    company: "GrowthLab",
    email: "marcus@growthlab.com",
    phone: "+1 (212) 555-0198",
    website: "growthlab.com",
    location: "New York, NY",
    industry: "Marketing",
    employees: 45,
    revenue: "$5M",
    status: "contacted",
    hotScore: 78,
    source: "import",
    addedAt: "2025-01-14",
    notes: "Interested in outbound sequences",
    social: { linkedin: "linkedin.com/in/marcusrivera" },
  },
  {
    id: "3",
    name: "Emily Park",
    title: "CEO",
    company: "BrightPath Consulting",
    email: "emily.park@brightpath.co",
    phone: "+1 (312) 555-0267",
    website: "brightpath.co",
    location: "Chicago, IL",
    industry: "Consulting",
    employees: 28,
    revenue: "$3.2M",
    status: "replied",
    hotScore: 85,
    source: "google-maps",
    addedAt: "2025-01-13",
    notes: "Responded positively, wants demo",
    social: { linkedin: "linkedin.com/in/emilypark" },
  },
  {
    id: "4",
    name: "James O'Brien",
    title: "Head of Sales",
    company: "DataScale",
    email: "james.o@datascale.ai",
    phone: "+1 (617) 555-0321",
    website: "datascale.ai",
    location: "Boston, MA",
    industry: "Data Analytics",
    employees: 200,
    revenue: "$28M",
    status: "meeting",
    hotScore: 97,
    source: "google-maps",
    addedAt: "2025-01-12",
    notes: "Meeting scheduled for demo",
    social: { linkedin: "linkedin.com/in/jamesobrien" },
  },
  {
    id: "5",
    name: "Lisa Thompson",
    title: "Operations Manager",
    company: "GreenBuild Solutions",
    email: "lisa.t@greenbuild.com",
    phone: "+1 (503) 555-0445",
    website: "greenbuild.com",
    location: "Portland, OR",
    industry: "Construction",
    employees: 85,
    revenue: "$12M",
    status: "new",
    hotScore: 45,
    source: "google-maps",
    addedAt: "2025-01-11",
    notes: "",
    social: { linkedin: "" },
  },
  {
    id: "6",
    name: "David Kim",
    title: "CTO",
    company: "NexaSoft",
    email: "david.kim@nexasoft.dev",
    phone: "+1 (512) 555-0598",
    website: "nexasoft.dev",
    location: "Austin, TX",
    industry: "Software",
    employees: 65,
    revenue: "$8M",
    status: "contacted",
    hotScore: 62,
    source: "google-maps",
    addedAt: "2025-01-10",
    notes: "Evaluating tools for Q1",
    social: { linkedin: "linkedin.com/in/davidkim" },
  },
  {
    id: "7",
    name: "Rachel Nguyen",
    title: "Founder",
    company: "UrbanNest Realty",
    email: "rachel@urbannest.com",
    phone: "+1 (305) 555-0678",
    website: "urbannest.com",
    location: "Miami, FL",
    industry: "Real Estate",
    employees: 15,
    revenue: "$2M",
    status: "new",
    hotScore: 55,
    source: "import",
    addedAt: "2025-01-09",
    notes: "",
    social: { linkedin: "" },
  },
  {
    id: "8",
    name: "Alex Petrov",
    title: "VP Marketing",
    company: "CloudVista",
    email: "alex.p@cloudvista.io",
    phone: "+1 (408) 555-0811",
    website: "cloudvista.io",
    location: "San Jose, CA",
    industry: "Cloud Services",
    employees: 150,
    revenue: "$20M",
    status: "replied",
    hotScore: 88,
    source: "google-maps",
    addedAt: "2025-01-08",
    notes: "Very interested, asked about pricing",
    social: { linkedin: "linkedin.com/in/alexpetrov" },
  },
];

export const mockDashboardStats = {
  totalLeads: 247,
  contacted: 89,
  replied: 34,
  openSequences: 12,
  leadVelocity: 18.5,
  replyRate: 38.2,
  meetingRate: 12.4,
  weeklyData: [
    { day: "Mon", leads: 12, replied: 4 },
    { day: "Tue", leads: 19, replied: 6 },
    { day: "Wed", leads: 8, replied: 3 },
    { day: "Thu", leads: 24, replied: 9 },
    { day: "Fri", leads: 15, replied: 5 },
    { day: "Sat", leads: 5, replied: 1 },
    { day: "Sun", leads: 3, replied: 1 },
  ],
  monthlyTrend: [
    { month: "Oct", leads: 45, contacted: 12, replied: 5 },
    { month: "Nov", leads: 62, contacted: 22, replied: 9 },
    { month: "Dec", leads: 58, contacted: 20, replied: 8 },
    { month: "Jan", leads: 82, contacted: 35, replied: 12 },
  ],
};

export const mockPipelineColumns = [
  {
    id: "new",
    title: "New Leads",
    color: "#1d6fa8",
    leadIds: ["1", "5", "7"],
  },
  {
    id: "contacted",
    title: "Contacted",
    color: "#996200",
    leadIds: ["2", "6"],
  },
  {
    id: "replied",
    title: "Replied",
    color: "#1a7a45",
    leadIds: ["3", "8"],
  },
  {
    id: "meeting",
    title: "Meeting Scheduled",
    color: "#0f0f0e",
    leadIds: ["4"],
  },
  {
    id: "won",
    title: "Won",
    color: "#1a7a45",
    leadIds: [],
  },
  {
    id: "lost",
    title: "Lost",
    color: "#b83232",
    leadIds: [],
  },
];

export const mockSequences = [
  {
    id: "seq-1",
    name: "Tech SaaS Outreach",
    status: "active",
    leadsCount: 45,
    sentCount: 38,
    replyCount: 14,
    createdAt: "2025-01-05",
    steps: 4,
  },
  {
    id: "seq-2",
    name: "Consulting Follow-up",
    status: "active",
    leadsCount: 22,
    sentCount: 15,
    replyCount: 6,
    createdAt: "2025-01-10",
    steps: 3,
  },
  {
    id: "seq-3",
    name: "Real Estate Cold",
    status: "draft",
    leadsCount: 0,
    sentCount: 0,
    replyCount: 0,
    createdAt: "2025-01-14",
    steps: 5,
  },
];

export type Lead = (typeof mockLeads)[number];
